### ISSUE TITLE
Data fields for contract

### ISSUE THREAD

**Issue by matthewglover** [worthwhile-charity/hack-day#35]
Can you confirm the data fields for each job match.

Currently we are using:
- Job id (some unique identifier - do you have one? if not we can generate our own)
- Job Match Status (to issue / issued / completed)
- Job Title
- Job Start Date
- Job End Date
- Employer Name
- Employer Company Number
- Employer Address
- Employee Name
- Employee Address

**Comment by robbiesemple** [comment]
Looks good. We don't currently have a job id, so feel free to create yourselves.

Possibly don't need Job End Date, or Employee Address - can you include them as non-mandatory fields?  Thanks

**Comment by matthewglover** [comment]
Thanks Robbie - will implement as per your proposal. 

If you decide to go ahead with a full implementation, then we can easily adjust the fields as required.
